### ISSUE TITLE
Some TLDs not working

### ISSUE THREAD

**Issue by ganti** [DigitaleGesellschaft/digiges-phplist3#5]
ignore this, see comment

********
Some TLDs like `cloud` are not valid tlds to subscribe to the newsletter.

i checked and found out that the source file is not downloadable, therefore we could try the following:
uncomment: lines 218, 219
comment lines 220, 221

https://github.com/phpList/phplist3/blob/495217f27e37dbb3ba0a3bd6812d3ea1477d4f5e/public_html/lists/admin/init.php#L218

as offline quickfix, we could add the tld `cloud`here:
https://github.com/phpList/phplist3/blob/495217f27e37dbb3ba0a3bd6812d3ea1477d4f5e/public_html/lists/admin/inc/userlib.php#L724

**Comment by ganti** [comment]
@rettichschnidi have a look, and if it works make a PR

**Comment by ganti** [comment]
even better, it is fixed in phplist: https://github.com/phpList/phplist3/issues/649
please do: System > Upgrade phpList and clicking update Top Level Domains.
then the missing tlds are imported

**Comment by rettichschnidi** [comment]
Done. How can you/we test this?

**Comment by rettichschnidi** [comment]
Reopened because this is still failing (https://www.phplist.com/files/tlds-alpha-by-domain.txt.md5 is missing)

**Comment by rettichschnidi** [comment]
.md5 file is now available
